### PR TITLE
Added PyPy support

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
This will require a bit more work.
On PyPy we can use psycopg2-cffi.
Let me clone that branch. The build will pass soon.

**Comment by thedrow** [comment]
I think pip is being silly here. Lemme check.

**Comment by thedrow** [comment]
Now it skips the damm Cython generation step. I'll get back to you on that.

**Comment by coleifer** [comment]
Closing for now, if you plan to re-open would you mind rebasing the existing commits into a single commit?

**Comment by thedrow** [comment]
I wouldn't. It doesn't work yet though.

**Comment by thedrow** [comment]
I mean I wouldn't mind rebasing...

**Comment by coleifer** [comment]
Cool, I guess I should ask: is this something you plan on continuing to hack on until it's all working? If so be happy to reopen and you can rebase when it's closer to being done.

**Pull request closed without merging**
