### PR TITLE
Add support for MySQL STRAIGHT_JOIN

### PR DESCRIPTION
**Pull request by D0d0**
Add support for mysql STRAIGHT_JOIN. Resolves https://github.com/coleifer/peewee/issues/842

### CODE REVIEW

**Comment by coleifer** [comment]
Going to pass.

**Comment by prav2019** [comment]
Is the feature available in the peewee now ?

**Comment by prav2019** [comment]
I see latest peewee version was added in Apr 23, 2020, so this one not yet released ???

**Comment by coleifer** [comment]
I did not merge this change.

**Comment by prav2019** [comment]
Any alternative way to include straight_join in peewee ?

**Comment by prav2019** [comment]
or is there a way to replace **select** with **select straight_join** once the query is built ? any solution related to this one is much appreciated thanks

**Comment by coleifer** [comment]
It seems like a very obscure mysql thing to try and hint the query-planner to use a certain ordering. I don't really plan on supporting or maintaining that functionality. I'd suggest tweaking your query or re-generating statistics.

**Comment by prav2019** [comment]
okay
thanks

**Pull request closed without merging**
