### PR TITLE
Added a pip cache to Travis

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by coleifer** [comment]
What's going on in this PR? I'm not sure I understand the differences here.

**Comment by thedrow** [comment]
It caches the compilation of the C extensions and also doesn't download pip dependencies.
The build as a result should be faster.

**Comment by coleifer** [comment]
Just looking at the build times it doesn't appear to have made a difference.

**Comment by coleifer** [comment]
Did a quick skim of the travis cache docs, I'm going to pass on this one.

**Pull request closed without merging**
