### PR TITLE
Add --ssl option to pwiz

### PR DESCRIPTION
**Pull request by mgalvey**
Refs #1336 

Tested locally with both supported mysql drivers and didn't run into any problems. DID NOT test that psycopg tries SSL by default, but the docs for the client library that psycopg uses say that it does: https://www.postgresql.org/docs/9.1/static/libpq-ssl.html. From that page:

> The default value for sslmode is prefer.

This enables only the most simple ssl mode (with no CA verification), but it at least gets you around the problem of a server configured only to allow secure connections.

### CODE REVIEW

**Comment by coleifer** [comment]
Going to pass on this, but thank you.

**Comment by mgalvey** [comment]
Is there anything that would make this or a feature like it suitable for inclusion in pwiz, or is this use case just something you're not interested in supporting?

**Comment by coleifer** [comment]
In 5...6 years you're the only person who's requested it :)

**Comment by azydevelopment** [comment]
@coleifer I guess I should say that we really need this. I'm not sure how we can use peewee in a anything with even mildly sensitive data without SSL. Basically, it's for the exact reason that @mgalvey was saying.

**Pull request closed without merging**
