### PR TITLE
querying.rst: update ManyToManyField module belong

### PR DESCRIPTION
**Pull request by franciscod**
ManyToManyField is now on the playhouse.fields module, docs were slightly misleading

### CODE REVIEW

**Comment by coleifer** [comment]
Is fields the right ref?

**Comment by franciscod** [comment]
No sir! It's extra-fields! fixing that up, sorry!

**Comment by franciscod** [comment]
push-forced the changes, but i've not yet built the docs locally so this is untested

**Comment by franciscod** [comment]
installed sphinx, `make html`, links are working! should I check anything else?

**Comment by coleifer** [comment]
Thanks a lot!

**Pull request merged**
