### PR TITLE
Update peewee.py

### PR DESCRIPTION
**Pull request by lvhaidong**
Add field comment info

### CODE REVIEW

**Comment by coleifer** [comment]
Nope. That's a mysql-only thing.

**Comment by lvhaidong** [comment]
How to set comment in the model, can be described in the database can see the details

**Comment by coleifer** [comment]
It is not supported by sqlite or postgres.

**Comment by lvhaidong** [comment]
I am use mysql, which field can be described in the database can see the details

**Comment by geonyoro** [comment]
Are you averse to adding dv-specific features?

**Comment by coleifer** [comment]
> Are you averse to adding dv-specific features?

Not at all, but they have to be added in such a way that they are compatible. This patch would break hard if a user added help_text on sqlite or postgres. That's not compatible.

**Pull request closed without merging**
