### PR TITLE
Fixed broken BlobField/BinaryField in MySQL

### LINKED ISSUE #818: BinaryField/BlobField/UUIDField is broken with MySQL
Looks like both `BlobField` and `BinaryField` in MySQL are actually broken, because MySQL expects a `max_length`, and thus all values are being truncated down to 1 byte.

The most obvious fix seems to be;

```
class BinaryField(BlobField):
    db_field = 'varbinary'

class FixedBinaryField(CharField):
    db_field = 'binary'    
```

The test should then probably be updated to include a `data` value comparison, and then add the appropriate database mappings after.

Submitting PR shortly

### PR DESCRIPTION
**Pull request by foxx**
Fixes #818

### CODE REVIEW

**Comment by foxx** [comment]
This will need sign off and review from @coleifer before merge. I'm about 90% happy with the code, but there could be some edge cases I haven't considered.

**Comment by coleifer** [comment]
I'm leaning towards killing off the binary field altogether.

**Comment by foxx** [comment]
@coleifer Yeah I just updated the original issue with my conclusion, lemme know your thoughts

**Comment by foxx** [comment]
Closing as per #818

**Pull request closed without merging**
