### PR TITLE
Add connection management documentation for Falcon

### PR DESCRIPTION
**Pull request by arpankapoor**
Middleware components in Falcon framework (http://falconframework.org/)
can be used to add database connection management.

### CODE REVIEW

**Comment by coleifer** [comment]
Does the response middleware method not need to return anything? (Or the request middleware for that matter)

**Comment by arpankapoor** [comment]
Nothing needs to be returned.

The middleware methods may modify the request and response objects passed in as parameters. These objects are routed to the appropriate responder method by Falcon.

See the docstring of the middleware methods [here](https://falcon.readthedocs.org/en/latest/api/middleware.html#middleware-components).

**Comment by coleifer** [comment]
Thanks!

**Comment by arivero** [comment]
Not sure if it should be documented, but calling db.close in the process_response kills the cursor, and then a response via stream will fail

**Pull request merged**
