### PR TITLE
fix InterfaceError when postgresql connection is closed

### PR DESCRIPTION
**Pull request by velom**
when `self._state.closed is False` and `self._state.conn.closed != 0`

### CODE REVIEW

**Comment by coleifer** [comment]
I'm unclear on why this patch is necessary. Granted, Peewee could do a lot more introspection to detect whether the connection is closed or not, but this method is intended more to refer to the "peewee" connection state rather than the "driver" connection state.

**Comment by coleifer** [comment]
I'm going to pass on this -- connections dying unexpectedly probably *should* raise an `InterfaceError`.

**Comment by velom** [comment]
I have described my situation at https://github.com/coleifer/peewee/pull/1779#issuecomment-436895926.
During some exceptions, `self._state.conn.closed` became non zero, but `self._state.closed` is still `False`.

**Comment by velom** [comment]
> I'm going to pass on this -- connections dying unexpectedly probably _should_ raise an `InterfaceError`.

By the way, when connection is dying, peewee doesn't switch `self._state.closed` to `True`.
So every next request will fail here
```python
def cursor(self, commit=None):
        if self.is_closed():
            self.connect()
        return self._state.conn.cursor()
```
because `self.is_closed()` returns `False`, but connection is dead (`self._state.conn.closed != 0`)

**Comment by coleifer** [comment]
Correct - it is necessary to implement reconnect logic.

**Comment by velom** [comment]
do you think, there is no bug in peewee in this case?

**Pull request closed without merging**
