### PR TITLE
Add interval field support for Postgres

### PR DESCRIPTION
**Pull request by alexlatchford**
I can add/amend the tests if you think this is a good approach.

PS. Sorry looks like my AutoPEP8 got in the way of the changes, I can remove if needs be.

### CODE REVIEW

**Comment by coleifer** [comment]
What Python data-type is used by psycopg2 to represent an interval in Postgres? I'd assume a `datetime.timedelta`? I'm good with merging the changes (though please rebase into a single commit and remove the PEP8 changes).

**Comment by alexlatchford** [comment]
Yep uses `timedelta` internally. Should be all handled transparently by `psycopg2` and the operations by the operators on `Node` from my initial tests.

Rebased as suggested and removed formatting.

**Comment by coleifer** [comment]
Looks like the test model differs from the model used in the test-case itself, which is causing the builds to fail. You mind fixing that, and maybe adding an integration test that actually creates the table and verifies the data and data-types being stored/retrieved from the DB?

**Comment by coleifer** [comment]
It was so close! Just needed to fix the tests up a bit. Any reason you closed this?

**Comment by alexlatchford** [comment]
Unfortunately the project I needed this for was cancelled and I'm unlikely to get around to fixing this up anytime soon so didn't want to clutter things up. Feel free to take it on if you think it's a good addition :)

**Comment by coleifer** [comment]
Thanks @alexlatchford -- I may do that when I've got a little free time. I appreciate the effort!

**Comment by coleifer** [comment]
Committed f4ebd78b990efc6f0fc57b9a4d81f0cd6ecdf276

**Pull request closed without merging**
