### PR TITLE
prefetch() now loads all foreign keys to given table

### PR DESCRIPTION
**Pull request by hedger**

### CODE REVIEW

**Comment by hedger** [comment]
Yay, all checks have passed.

**Comment by coleifer** [comment]
I've pushed a branch that has some of your changes integrated, 89cd2c4f74a526591f3804d04b2252c489be5432

**Comment by hedger** [comment]
That's great, thanks!

**Comment by coleifer** [comment]
Pushed 2f028c32225c5aad9b97f0f451b9d238c3846e0d to the `multiprefetch` branch. Things aren't working quite right in the test-case. I think the identity map needs to differentiate things by field, but haven't dug into it too much yet.

**Comment by coleifer** [comment]
Got things fixed and have merged into master.

**Pull request closed without merging**
